### PR TITLE
Added test spec to make sure named variables only match single words #144

### PR DESCRIPTION
**Pull request by evaldosantos**
Added new test spec to make sure that named variables only match any sentence with exactly one word replacing the named variable.

### CODE REVIEW

**Comment by evaldosantos** [comment]
I've coding for a while now, and I was searching some way to start to contribute in a project. I'd like to thank you by this opportunity. I made my first pull request, also this was my first contact in a project using tests. Really a great experience. It was fun, thanks.

**Comment by TalAter** [comment]
Thanks for the contribution @evaldosantos 

A couple of things:
- The first part of your test right now duplicates what is already being tested in the tests just before it (that it correctly matches when the named variable is there), and so isn't needed.
- The last part of your test tests another condition I completely forgot to test for. Nice. :+1:  It should be in its own spec.

Each spec should test for just one thing, and its description should describe a single behaviour:
- :white_check_mark: annyang.addCommands should match commands with named variables.
- :white_check_mark: **annyang.addCommands should not match commands with more than one word as the named variable.**
- :white_check_mark: **annyang.addCommands should not match commands with no text for a named variable**

This creates tests that can be read as documentation:


It also makes the test's code simpler to understand and read when they just test one thing:

**Comment by evaldosantos** [comment]
Sorry for delay, I don't have internet connection on weekends. So I only need change the 'it' part? I checked the code, and its duplicated. Sorry, english isn't my first language.

**Comment by TalAter** [comment]
No problem @evaldosantos :+1: 

- No need to test for match (already tested before)
- Separate into two tests: test with 2 words as named variable, test with 0 words as named variable

Something like this (I didn't test it):
````javascript
it('should not match commands with more than one word in the position of a named variable', function () {
   var spyOnMatch = jasmine.createSpy();
   annyang.addCommands(
     {
       'Time for some :description heroics': spyOnMatch
     }
   );
   recognition.say('Time for some thrilling and fun heroics');
   expect(spyOnMatch).not.toHaveBeenCalled();
});

it('should not match commands with nothing in the position of a named variable', function () {
   var spyOnMatch = jasmine.createSpy();
   annyang.addCommands(
     {
       'Time for some :description heroics': spyOnMatch
     }
   );
   recognition.say('Time for some heroics');
   expect(spyOnMatch).not.toHaveBeenCalled();
});
````

Finally, update your code by pulling changes from master branch, and fix conflicts.

**Comment by TalAter** [comment]
Great stuff!

I'm glad you were able to think of the second case (testing when the word is missing).

Congratulations on your first :octocat: pull request!

**Pull request merged**
