### PR TITLE
Fix markdown file grammar errors

### PR DESCRIPTION
**Pull request by rocketbear27**
I fixed a few grammar errors I found throughout the markdown files.

## Description
I fixed a few grammar errors I found throughout the markdown files.

## Motivation and Context
This improves markdown clarity.

## How Has This Been Tested?
By rereading the file

## Types of changes

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X ] My code follows the code style of this project.
- [ X] My change requires a change to the documentation.
- [ X] I have updated the documentation accordingly.
- [ X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by TalAter** [comment]
Thank you for the help @rocketbear27 

Serial comma forever! ✊ 

One important thing before I can merge this:

The file `docs/README.md` is generated automatically from the comments in `src/annyang.js`. That means that your changes to `docs/README.md` will be overwritten the next time annyang's build script runs.

Could you make the changes directly in `src/annyang.js` and then run `npm start` (you can ctrl+c out of it as soon as it opens the web browser). At this point your changes should be in both `docs/README.md` and `src/annyang.js`. You can then commit both files.

Note that I added some changes directly on top of your changes to `docs/README.md` (you can see them here: e170f1ce8b83e9dbd4e04e939777217f99c9326a). The important change is where I am using SpeechRecognition (vs. speech recognition) to refer to the browser's implementation of the [SpeechRecognition interface](https://w3c.github.io/speech-api/speechapi.html#speechreco-section).

**Comment by rocketbear27** [comment]
Sure, let me fix it as soon as possible

**Comment by TalAter** [comment]
only `src/annyang.js` and `/docs/README.md`

**Comment by rocketbear27** [comment]
I committed `src/annyang.js` and `docs/README.md`

**Comment by TalAter** [comment]
Merged! 🚀 

Thank you so much for the help 👍

**Comment by rocketbear27** [comment]
Thank you for merging!

**Pull request merged**
