### PR TITLE
Add soundstart and speechstart event callbacks

### PR DESCRIPTION
**Pull request by remybach**
Just thought these would be useful - for example - when you want to show feedback that there's at least something going on between when you start talking and when there's a result. This is only when `continuous` is true (or only on `http` as it were).

Something like this:

```
annyang.addCallback("speechstart", function() {
  $("body").addClass("is-listening");
});
annyang.addCallback("result", function() {
  $("body").removeClass("is-listening");
});
```

### CODE REVIEW

**Comment by TalAter** [comment]
Thanks @remybach I'm experimenting with your code.

A few thoughts
* I don't see any difference between the implementation of soundstart and speechstart in Chrome. Chrome seems to always fire both, no matter if I speak or just make a noise. Do you see a need to add both?
* Why use this only in continuous mode? When it is continuous it will only be fired the first time a sound is heard... and then nothing will be fired the next time. Wouldn't your sample code above, running with continuous mode, add the class when it first hears something, then remove it on result... but then it won't appear ever again even when sound is being heard and analyzed?
I actually much prefer the behaviour it exhibits in non-continuous mode... It fires every time it starts detecting sound... then the user can decide if he wants to do something just the first time, or every time.

**Comment by remybach** [comment]
Thanks for the response :smile:

+ The difference is that `soundstart` should be for _any_ sound that's picked up (low latency), whereas `speechstart` is when the engine has determined that it's definitely hearing speech. Given the aim of this library it might make sense to only have `speechstart`, but there may be cases where giving an indication that it's listening may be useful to someone at some point.
+ Yeah, I was wrong about the continuous mode. I realised earlier that I had the wrong way around in my head so you're right. It's better to just always do it.

Let me know your thoughts and I can update the PR accordingly.

**Comment by TalAter** [comment]
* Yes, that is the difference according to the spec... in practice though, since the recognition is done entirely online [citation needed], and the event needs to be fired off immediately, Chrome just fires both. So the difference is moot.
I actually prefer `soundstart` because of this imperfect implementation of the spec. If it fires speechstart when the user's dog barks, it is misleading.
* I don't like the idea of having it behave so differently in continuous and non-continuous modes... it might be very confusing for the developer (it sure got us both). Do you have any ideas on how to simplify this?
Right now the behaviour I can think of is:
  * In non-continuous mode (https) the soundstart event will start every time a new block of sounds is recognized - multiple events.
  * In continuous mode (http) the soundstart event will only fire the first time sound is heard.

**Comment by remybach** [comment]
+ Yeah, I tested it after your previous reply and there seems to be no difference (clicking my fingers fired the `speechstart` event). Happy to just go with `soundstart` in that case.
+ I think the best thing might be to always fire the event rather and then let the dev decide how they want to handle it. It perhaps just needs a note in the documentation or something?

**Comment by AbdullahNauman** [comment]
This type of capability, would aid be greatly in my current project. Has this been yet implemented into the release version of the library. If not then when would we be seeing an implementation of this functionality.

**Comment by TalAter** [comment]
I opened a bug with the Chromium team a few months ago to fix the behaviour of the speechstart event. It is currently implemented not according to spec (or reason). Feel free to go to that bug report and ask them for a progress report - https://code.google.com/p/chromium/issues/detail?id=572697&thanks=572697&ts=1451323087

**Comment by TalAter** [comment]
@remybach I think the best course of action right now, since a fix to Chrome's behaviour seems to be taking too long is to just to add a `soundstart` and a `soundend` event as we discussed. annyang should treat continuous and non continuous mode the same.

Would you like to update the pull request with this, and add the proper tests? If not, I can do it.

**Comment by remybach** [comment]
Apologies for taking long to reply @TalAter... I unfortunately don't have much time to do this at the moment so if you could take over it would be much appreciated!

**Comment by TalAter** [comment]
Added the `soundstart` event in [v2.6.0](https://github.com/TalAter/annyang/releases/tag/v2.6.0) which was just released.

You can see a sample use case for this with source code in the FAQ - [Can I detect when the user starts and stops speaking?](#can-i-detect-when-the-user-starts-and-stops-speaking)

@remybach - Thank you for the help in figuring this one out and implementing it!

**Pull request closed without merging**
