### PR TITLE
Resolves #210 add behavior to accept command object that does not have a regexp property

### LINKED ISSUE #210: Allow command object to work for commands which do not have a regexp
I want to attach some other application-related properties to my command object.

Therefore, command object signatures that look like
```javascript
'word': function() { ... }
```
I am converting to signatures like
```javascript
'word': {
  callback: function() { ... },
  otherProp: 1
}
```
The problem is that `annyang` doesn't treat these as equivalent. It will not load command objects like shown in the second signature. It will only load command objects which look like:
```javascript
':word': {
  regexp: 'word',
  callback: function() { ... },
  otherProp: 1
}
```

## Expected Behavior
It should accept command objects like either of the first two shown above. This should work regardless of whether there is a regexp requirement or not.

## Current Behavior
described above. 

## Possible Solution
haven't looked yet 

## Steps to Reproduce (for bugs)
described above

## Context
described above

## Your Environment
n/a

### PR DESCRIPTION
**Pull request by thurt**
## Description

change `annyang.addCommands`
adds two tests

## Motivation and Context

see #210 . this would allow an extra form of command object to be valid.

## How Has This Been Tested?

The new tests currently do NOT pass. I don't understand why.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

…perty

### CODE REVIEW

**Comment by thurt** [comment]
> Can you share and example of why and how you need to use the extra properties on the command objects? This should help in implementing this in a way that will benefit the most users.

I am treating the command phrase as a namespace for some other application functions, such as a function for validating/updating/retrieving backend data and a function for updating the DOM. I want to associate these functions with the command phrase.

Some quick notes:
I have looked at `annyang.addCommands` and it doesn't appear to check for any other properties, so it shouldn't be a problem to add other properties anyways.

The actual problem appears to be that it only accepts a command object if it also has a regexp property. One way around this limitation is to always add a regexp property. However, this would be circumventing all of the built-in functionality of `commandToRegExp`
```javascript
'word': {
  regexp: /^word$/i,
  callback: function() { ... }
}
```

**Comment by thurt** [comment]
On second thought, I may actually precompile my command objects--so this feature may not be necessary. 

Example: my source code looks like
```javascript
'word': {
  callback: function() { ... },
  validateWithBackend: function() { ... },
  updateDom: function () { ... }
}
```
After pre-compiling with a wrapper I get something like
```javascript
'word': function wrapper() {
   callback()
   validateWithBackend()
   updateDom()
}
```

I still think this feature makes sense because these two should be treated equivalent:
```javascript
'word': function() { ... }

'word': {
  callback: function() { ... }
}
```

**Comment by TalAter** [comment]
As you say, you can achieve the same by just placing the logic in your callback function. It seems like a better place to put your application specific logic, than in annyang's command object.

Correct me if I am wrong, but I don't see a very common use case here. Not one which would make sense to change annyang's API for all users.

I know the current API for passing regex commands is a bit weird. But it was done after much consideration to avoid breaking backwards functionality, and to keep the most common use case as simple as possible (i.e. `'my :command': function(){}`)

Please let me know if you have any other ideas, or need any other help. Thanks for taking the time to send a :octocat: pull request! :+1:

**Comment by thurt** [comment]
I can understand keeping it as simple as possible. Thanks for taking a look anyways!

**Pull request closed without merging**
