### PR TITLE
#142 Added test for removing commands with named variable

### PR DESCRIPTION
**Pull request by siawyoung**
I added a test for removing a command with named variables - as mentioned in the issue, the test is very similar to an existing test for removing a command with optional words.

### CODE REVIEW

**Comment by siawyoung** [comment]
This turned out to be way more fun than I expected - if no one takes up the remaining first-timer issues in the next couple of hours, can I go ahead and tackle them?

And thank you so much for creating opportunities like this for people like us. I've been coding for a while now but I just could never find a way to fit myself into a OSS community. The prospect of it just seems incredibly daunting... I suspect I may have a strong and persistent bout of imposter syndrome.

**Comment by TalAter** [comment]
Thanks for the contribution @siawyoung. Looks great! :+1:

I'm really glad you had fun with it, and really hope it will encourage you to contribute more!

As for the other *first-timers-only* issues, I would prefer to leave the opportunity for people who haven't contributed yet to open source. There's plenty of other open issues you can tackle, and I'll be glad to provide any help you need.

As for the imposter syndrome... I'm afraid that never goes away :blush:

**Comment by TalAter** [comment]
Hey @siawyoung, I've got a bigger one for you, if you'd like.

I've just created #147. Hope it's interesting for you :+1:

**Comment by siawyoung** [comment]
I'm all over it 🙌

**Comment by TalAter** [comment]
Thanks @siawyoung 

How about we tackle some recursion next?

The test you added makes sure the callback is fired when there is a match... but we need to also make sure it doesn't get called when there is no match (this isn't a given, as the `match` callback gets called in both cases).

Would you [create a new issue](https://github.com/TalAter/annyang/issues/new) for first-timers-only to add this test, so that someone new can build on your contribution and get their first pull request in open source?

You see? Recursion! :smile: 

(#152 is for testing something similar but for `resultNoMatch`)

**Comment by TalAter** [comment]
:sunglasses: Issue 154 looks awesome!

**Pull request merged**
