### PR TITLE
Added test spec to test sentences with optional words. Issue #145

### PR DESCRIPTION
**Pull request by Endi1**
New test spec now tests that a sentence with an optional word only
matches options with and without that word.

### CODE REVIEW

**Comment by TalAter** [comment]
Looks good @Endi1
:sparkles: 1 million bonus points for using *gorram*! :sparkles:

One thing... your test right now duplicates what is already being tested in the two tests just before it. 

There's no need to test for it matching when the optional word is and isn't there, just to make sure it doesn't match when there's a different word.

Each spec should test for one thing, and it's description should describe a single behaviour:
- :white_check_mark: annyang.addCommands should match commands with optional words when the word is in the sentence.
- :white_check_mark: annyang.addCommands should match commands with optional words when the word is not in the sentence
- :white_check_mark: **annyang.addCommands should not match commands with optional words when a different word is in the sentence** :+1: 

This creates tests that can be read as documentation:


It also makes the test's code simpler to understand and read:

**Comment by Endi1** [comment]
@TalAter thanks for the help!

You are right, I should have thought of that myself :). Pushed a new commit, it should be fixed now.

**Comment by TalAter** [comment]
Hi @Endi1, thanks for the quick update.

A few more points.

- Did you run the tests after the last change? I just ran them and they fail.  I believe the problem is `expect(spyOnMatch).toHaveBeenCalledTimes(0);` doesn't work because of a bug in Jasmine. If you change it to `expect(spyOnMatch).not.toHaveBeenCalled();`, it works.
- Your indentation is done with tabs, while the rest of the project uses spaces. When contributing to an open source project, it is very important to keep that project's existing coding standards (there isn't a right or wrong coding style... it's just about keeping it consistent). Change the tabs to 2 spaces each.
What IDE/editor do you use to write the code? There are some that will analyze the file you are editing and change their setting to keep the current file's style. Others will even notice that there is a `.editorconfig` file in the project and get the code style from that (even better).
- Your pull request had conflicts with the master branch. That means the project maintainer can't accept your pull request automatically. Update your local branch with changes from the remote, resolve the conflicts, and update the pull request.

**Comment by TalAter** [comment]
Awesome @Endi1 :trophy: 

Congrats on getting more seriously into open source! I hope this is the first contribution of many!

Thank you :heart:

**Comment by Endi1** [comment]
Thank you for giving me the chance, I had been looking to sink my teeth into FOSS projects for a while but couldn't find a good starting point :)

**Pull request merged**
