### PR TITLE
typings

### PR DESCRIPTION
**Pull request by theluk**
typings in the .d.ts format to enhance type safety and autocompletion for TypeScript based apps
## Description

I added a annyang.d.ts file reflecting the public api. 
## TODO

I copied most of the comments, and enhanced them. Altough copying is a ugly solution, i did not find a common practice how to do it better. 
## Motivation and Context

I wanted to use annyang in a angular2 project.
## How Has This Been Tested?

there are no tests right now, as I have no experience in how to test type definition.  Any help would be nice. @typings
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by semagarcia** [comment]
Which is the state of that PR?

**Comment by jkuri** [comment]
any progress on this?

**Comment by hisham** [comment]
+1 - this is needed.

**Comment by hisham** [comment]
fyi I updated these typings and created a pull request in DefinitelyTyped project as maintainer of this project doesn't seem to be making this a priority. My pull request is at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19031

**Comment by TalAter** [comment]
Hi @hisham,

If you'd like to send a pull request here as well I'll be happy to check it out. Hopefully, it can help a lot of our users.

Thank you.

**Comment by hisham** [comment]
Thanks @TalAter, now that the annyang type definitions is in DefinitelyTyped, we don't really need to add it to annyang package, although it is preferred from DefinitelyTyped perspective, but no real impact on anyone.

**Comment by theluk** [comment]
I think it is better to to make merge request! Definitely Typed is kind of
deprecated if the project owner is willed to merge...

**Comment by hisham** [comment]
@theluk maybe you're referring to https://github.com/typings/typings? That's deprecated but as far as I see https://github.com/DefinitelyTyped/DefinitelyTyped is very much active and supported. 

This is what they say in their documentation - I did the 2nd paragraph since this pull request didn't get merged and I needed the annyang type definitions.

> Create a new package
> 
> If you are the library author, or can make a pull request to the library, bundle types instead of publishing to DefinitelyTyped.
> 
> If you are adding typings for an NPM package, create a directory with the same name. If the package you are adding typings for is not on NPM, make sure the name you choose for it does not conflict with the name of a package on NPM. (You can use npm info foo to check for the existence of the foo package.)

**Comment by theluk** [comment]
Please make a pull request as the maintainer should have the chance to
merge it so that users do not have to make two separate dependencies.

**Comment by theluk** [comment]
And only if it gets merged you may remove it from @types.

**Comment by TalAter** [comment]
I agree, @theluk.

I think it is best if we keep it within this package. This has several benefits:
1. Users don't have to figure out where to get types from a separate dependency, and they don't have to add two dependencies.
2. The types can be kept up to date and in sync with each of annyang's versions as the API changes.

**Comment by hisham** [comment]
Done - see https://github.com/TalAter/annyang/pull/304.

**Comment by TalAter** [comment]
@theluk, @semagarcia, @jkuri 
I would appreciate your advice on #304

**Pull request closed without merging**
